name = "GeoRegions"
uuid = "b001f823-fa75-4bff-bf55-6610c8f3688a"
authors = ["natgeo-wong <natgeo.wong@outlook.com>"]
version = "4.0.2"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
PolygonOps = "647866c9-e3ac-4575-94e7-e3d426903924"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"

[compat]
GeometryBasics = "0.3, 0.4"
PolygonOps = "0.1"
PrettyTables = "1"
julia = "^1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
